config: make sure BITSxx is defined
This allows us to fail nicely in the event word size is unknown instead of this:

  In file included from ../../src/cforth/embed/mallocembed.c:3:
  ../../src/cforth/forth.h:21:5: error: unknown type name 'u_cell'
     21 |     u_cell magic, serial, dstart, dsize, ustart, usize, entry, res1;
        |     ^~~~~~
  ../../src/cforth/forth.h:62:24: error: unknown type name 'u_cell'; did you mean 'cell'?